#ifndef _INCLUDE_SIGSEGV_MOD_AI_MVM_DEFENDER_BOTS_UPGRADES_SNIPER_H_
#define _INCLUDE_SIGSEGV_MOD_AI_MVM_DEFENDER_BOTS_UPGRADES_SNIPER_H_


namespace Mod::AI::MvM_Defender_Bots
{
	
}


#endif
