#include "addr/addr.h"
#include "util/util.h"


static CAddr_Func_KnownVTOff addr_INER_FirstContainedResponder(       "INextBotEventResponder::FirstContainedResponder",        "_ZNK22INextBotEventResponder23FirstContainedResponderEv",                                "[VT] INextBotEventResponder", 0x01);
static CAddr_Func_KnownVTOff addr_INER_NextContainedResponder(        "INextBotEventResponder::NextContainedResponder",         "_ZNK22INextBotEventResponder22NextContainedResponderEPS_",                               "[VT] INextBotEventResponder", 0x02);
static CAddr_Func_KnownVTOff addr_INER_OnLeaveGround(                 "INextBotEventResponder::OnLeaveGround",                  "_ZN22INextBotEventResponder13OnLeaveGroundEP11CBaseEntity",                              "[VT] INextBotEventResponder", 0x03);
static CAddr_Func_KnownVTOff addr_INER_OnLandOnGround(                "INextBotEventResponder::OnLandOnGround",                 "_ZN22INextBotEventResponder14OnLandOnGroundEP11CBaseEntity",                             "[VT] INextBotEventResponder", 0x04);
static CAddr_Func_KnownVTOff addr_INER_OnContact(                     "INextBotEventResponder::OnContact",                      "_ZN22INextBotEventResponder9OnContactEP11CBaseEntityP10CGameTrace",                      "[VT] INextBotEventResponder", 0x05);
static CAddr_Func_KnownVTOff addr_INER_OnMoveToSuccess(               "INextBotEventResponder::OnMoveToSuccess",                "_ZN22INextBotEventResponder15OnMoveToSuccessEPK4Path",                                   "[VT] INextBotEventResponder", 0x06);
static CAddr_Func_KnownVTOff addr_INER_OnMoveToFailure(               "INextBotEventResponder::OnMoveToFailure",                "_ZN22INextBotEventResponder15OnMoveToFailureEPK4Path17MoveToFailureType",                "[VT] INextBotEventResponder", 0x07);
static CAddr_Func_KnownVTOff addr_INER_OnStuck(                       "INextBotEventResponder::OnStuck",                        "_ZN22INextBotEventResponder7OnStuckEv",                                                  "[VT] INextBotEventResponder", 0x08);
static CAddr_Func_KnownVTOff addr_INER_OnUnStuck(                     "INextBotEventResponder::OnUnStuck",                      "_ZN22INextBotEventResponder9OnUnStuckEv",                                                "[VT] INextBotEventResponder", 0x09);
static CAddr_Func_KnownVTOff addr_INER_OnPostureChanged(              "INextBotEventResponder::OnPostureChanged",               "_ZN22INextBotEventResponder16OnPostureChangedEv",                                        "[VT] INextBotEventResponder", 0x0a);
static CAddr_Func_KnownVTOff addr_INER_OnAnimationActivityComplete(   "INextBotEventResponder::OnAnimationActivityComplete",    "_ZN22INextBotEventResponder27OnAnimationActivityCompleteEi",                             "[VT] INextBotEventResponder", 0x0b);
static CAddr_Func_KnownVTOff addr_INER_OnAnimationActivityInterrupted("INextBotEventResponder::OnAnimationActivityInterrupted", "_ZN22INextBotEventResponder30OnAnimationActivityInterruptedEi",                          "[VT] INextBotEventResponder", 0x0c);
static CAddr_Func_KnownVTOff addr_INER_OnAnimationEvent(              "INextBotEventResponder::OnAnimationEvent",               "_ZN22INextBotEventResponder16OnAnimationEventEP11animevent_t",                           "[VT] INextBotEventResponder", 0x0d);
static CAddr_Func_KnownVTOff addr_INER_OnIgnite(                      "INextBotEventResponder::OnIgnite",                       "_ZN22INextBotEventResponder8OnIgniteEv",                                                 "[VT] INextBotEventResponder", 0x0e);
static CAddr_Func_KnownVTOff addr_INER_OnInjured(                     "INextBotEventResponder::OnInjured",                      "_ZN22INextBotEventResponder9OnInjuredERK15CTakeDamageInfo",                              "[VT] INextBotEventResponder", 0x0f);
static CAddr_Func_KnownVTOff addr_INER_OnKilled(                      "INextBotEventResponder::OnKilled",                       "_ZN22INextBotEventResponder8OnKilledERK15CTakeDamageInfo",                               "[VT] INextBotEventResponder", 0x10);
static CAddr_Func_KnownVTOff addr_INER_OnOtherKilled(                 "INextBotEventResponder::OnOtherKilled",                  "_ZN22INextBotEventResponder13OnOtherKilledEP20CBaseCombatCharacterRK15CTakeDamageInfo",  "[VT] INextBotEventResponder", 0x11);
static CAddr_Func_KnownVTOff addr_INER_OnSight(                       "INextBotEventResponder::OnSight",                        "_ZN22INextBotEventResponder7OnSightEP11CBaseEntity",                                     "[VT] INextBotEventResponder", 0x12);
static CAddr_Func_KnownVTOff addr_INER_OnLostSight(                   "INextBotEventResponder::OnLostSight",                    "_ZN22INextBotEventResponder11OnLostSightEP11CBaseEntity",                                "[VT] INextBotEventResponder", 0x13);
static CAddr_Func_KnownVTOff addr_INER_OnSound(                       "INextBotEventResponder::OnSound",                        "_ZN22INextBotEventResponder7OnSoundEP11CBaseEntityRK6VectorP9KeyValues",                 "[VT] INextBotEventResponder", 0x14);
static CAddr_Func_KnownVTOff addr_INER_OnSpokeConcept(                "INextBotEventResponder::OnSpokeConcept",                 "_ZN22INextBotEventResponder14OnSpokeConceptEP20CBaseCombatCharacterPKcP11AI_Response",   "[VT] INextBotEventResponder", 0x15);
static CAddr_Func_KnownVTOff addr_INER_OnWeaponFired(                 "INextBotEventResponder::OnWeaponFired",                  "_ZN22INextBotEventResponder13OnWeaponFiredEP20CBaseCombatCharacterP17CBaseCombatWeapon", "[VT] INextBotEventResponder", 0x16);
static CAddr_Func_KnownVTOff addr_INER_OnNavAreaChanged(              "INextBotEventResponder::OnNavAreaChanged",               "_ZN22INextBotEventResponder16OnNavAreaChangedEP8CNavAreaS1_",                            "[VT] INextBotEventResponder", 0x17);
static CAddr_Func_KnownVTOff addr_INER_OnModelChanged(                "INextBotEventResponder::OnModelChanged",                 "_ZN22INextBotEventResponder14OnModelChangedEv",                                          "[VT] INextBotEventResponder", 0x18);
static CAddr_Func_KnownVTOff addr_INER_OnPickUp(                      "INextBotEventResponder::OnPickUp",                       "_ZN22INextBotEventResponder8OnPickUpEP11CBaseEntityP20CBaseCombatCharacter",             "[VT] INextBotEventResponder", 0x19);
static CAddr_Func_KnownVTOff addr_INER_OnDrop(                        "INextBotEventResponder::OnDrop",                         "_ZN22INextBotEventResponder6OnDropEP11CBaseEntity",                                      "[VT] INextBotEventResponder", 0x1a);
static CAddr_Func_KnownVTOff addr_INER_OnActorEmoted(                 "INextBotEventResponder::OnActorEmoted",                  "_ZN22INextBotEventResponder13OnActorEmotedEP20CBaseCombatCharacteri",                    "[VT] INextBotEventResponder", 0x1b);
static CAddr_Func_KnownVTOff addr_INER_OnCommandAttack(               "INextBotEventResponder::OnCommandAttack",                "_ZN22INextBotEventResponder15OnCommandAttackEP11CBaseEntity",                            "[VT] INextBotEventResponder", 0x1c);
static CAddr_Func_KnownVTOff addr_INER_OnCommandApproach_vec(         "INextBotEventResponder::OnCommandApproach(vec)",         "_ZN22INextBotEventResponder17OnCommandApproachERK6Vectorf",                              "[VT] INextBotEventResponder", 0x1d);
static CAddr_Func_KnownVTOff addr_INER_OnCommandApproach_ent(         "INextBotEventResponder::OnCommandApproach(ent)",         "_ZN22INextBotEventResponder17OnCommandApproachEP11CBaseEntity",                          "[VT] INextBotEventResponder", 0x1e);
static CAddr_Func_KnownVTOff addr_INER_OnCommandRetreat(              "INextBotEventResponder::OnCommandRetreat",               "_ZN22INextBotEventResponder16OnCommandRetreatEP11CBaseEntityf",                          "[VT] INextBotEventResponder", 0x1f);
static CAddr_Func_KnownVTOff addr_INER_OnCommandPause(                "INextBotEventResponder::OnCommandPause",                 "_ZN22INextBotEventResponder14OnCommandPauseEf",                                          "[VT] INextBotEventResponder", 0x20);
static CAddr_Func_KnownVTOff addr_INER_OnCommandResume(               "INextBotEventResponder::OnCommandResume",                "_ZN22INextBotEventResponder15OnCommandResumeEv",                                         "[VT] INextBotEventResponder", 0x21);
static CAddr_Func_KnownVTOff addr_INER_OnCommandString(               "INextBotEventResponder::OnCommandString",                "_ZN22INextBotEventResponder15OnCommandStringEPKc",                                       "[VT] INextBotEventResponder", 0x22);
static CAddr_Func_KnownVTOff addr_INER_OnShoved(                      "INextBotEventResponder::OnShoved",                       "_ZN22INextBotEventResponder8OnShovedEP11CBaseEntity",                                    "[VT] INextBotEventResponder", 0x23);
static CAddr_Func_KnownVTOff addr_INER_OnBlinded(                     "INextBotEventResponder::OnBlinded",                      "_ZN22INextBotEventResponder9OnBlindedEP11CBaseEntity",                                   "[VT] INextBotEventResponder", 0x24);
static CAddr_Func_KnownVTOff addr_INER_OnTerritoryContested(          "INextBotEventResponder::OnTerritoryContested",           "_ZN22INextBotEventResponder20OnTerritoryContestedEi",                                    "[VT] INextBotEventResponder", 0x25);
static CAddr_Func_KnownVTOff addr_INER_OnTerritoryCaptured(           "INextBotEventResponder::OnTerritoryCaptured",            "_ZN22INextBotEventResponder19OnTerritoryCapturedEi",                                     "[VT] INextBotEventResponder", 0x26);
static CAddr_Func_KnownVTOff addr_INER_OnTerritoryLost(               "INextBotEventResponder::OnTerritoryLost",                "_ZN22INextBotEventResponder15OnTerritoryLostEi",                                         "[VT] INextBotEventResponder", 0x27);
static CAddr_Func_KnownVTOff addr_INER_OnWin(                         "INextBotEventResponder::OnWin",                          "_ZN22INextBotEventResponder5OnWinEv",                                                    "[VT] INextBotEventResponder", 0x28);
static CAddr_Func_KnownVTOff addr_INER_OnLose(                        "INextBotEventResponder::OnLose",                         "_ZN22INextBotEventResponder6OnLoseEv",                                                   "[VT] INextBotEventResponder", 0x29);
