#ifndef _INCLUDE_SIGSEGV_MOD_UTIL_OVERLAY_SHARED_H_
#define _INCLUDE_SIGSEGV_MOD_UTIL_OVERLAY_SHARED_H_


enum OverlayType : uint8_t
{
	CLEAR,
	BOX,
	BOX_ANGLES,
	SWEPT_BOX,
	LINE,
	TRIANGLE,
	ENTITY_TEXT,
	ENTITY_TEXT_AT_POSITION,
	GRID,
	TEXT,
	SCREEN_TEXT,
	CROSS3D_EXT,
	CROSS3D_SIZE,
	CROSS3D_ORIENTED_ANG,
//	CROSS3D_ORIENTED_MAT,
//	DRAW_TICK_MARKED_LINE,
//	DRAW_GROUND_CROSSHAIR_OVERLAY,
	HORZ_ARROW,
	YAW_ARROW,
	VERT_ARROW,
	AXIS,
	SPHERE,
	CIRCLE_ANG,
	CIRCLE_AXES,
	SPHERE_ANG,
};
constexpr int OVERLAY_TYPE_BITS = 5;

constexpr int ENTITY_ID_BITS = 12;

constexpr float MAX_OVERLAY_DIST_SQR = 90000000.0f;


#endif
